"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "pt" | "es";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

type TranslationMap = {
    [key: string]: string;
};

const translations: Record<Language, TranslationMap> = {
    en: {
        dashboard: "Dashboard",
        send: "Send",
        receive: "Receive",
        history: "History",
        settings: "Settings",
        profile: "Profile",
        available_balance: "Available Balance",
        reserved_balance: "Reserved Balance",
        recent_transactions: "Recent Transactions",
        quick_actions: "Quick Actions",
        send_points: "Send Points",
        buy: "Buy",
        view_all: "View All",
        cashback_program: "Cashback Program",
        welcome: "Welcome",
        operational_system: "Operational System",
        premium_user: "Premium User",
        logout: "Log out",
        send_pix: "Send PIX",
        points_to_cash: "Points to Cash",
        schedule: "Schedule",
        future_payments: "Future Payments",
        cashback_ready: "You have 350 points ready for redemption.",
        view_details: "View Details",
        admin_panel: "Admin Panel",
        administration: "Administration",
        managing_director: "Managing Director",
        command_center: "Command Center",
        overview: "Overview",
        members: "Members",
        financial_ledger: "Financial Ledger",
        auditing: "Auditing",
        gross_volume: "Gross Volume (GMV)",
        revenue_spread: "Revenue (Spread)",
        avg_ticket: "Average Ticket",
        daily_flow: "Settled Today",
        sales_performance: "Sales Performance Flow",
        sales_desc: "Consolidated volume by capture method",
        conversion_rate: "Conversion Rate",
        payment_efficiency: "Payment Efficiency",
        export_ledger: "Export Ledger",
        search_accounts: "Search accounts...",
        risk_status: "Risk Status",
        available_balance_admin: "Available Balance",
        actions: "Actions",
        pix_instant: "Instant Settlement",
        boleto_d2: "D+2 Liquidation",
        pointify_links: "Pointify Links",
        backoffice: "Backoffice",
        users: "Users",
        finances: "Finances",
        operational_system_label: "OPERATIONAL SYSTEM",
        main_menu_label: "MAIN MENU",
        logout_label: "Log out",
        total_control: "Total Control",
        active_status: "Active",
        admin_root: "Admin Root",
        pointify_user: "Pointify User",
        online_now: "Online now",
        seen_days_ago: "Seen 2 days ago",
        revoke: "Revoke",
        notifications: "Notifications",
        lang_region: "Language & Region",
        connected_devices: "Connected Devices",
        discard: "Discard",
        save_preferences: "Save Preferences",
        how_it_works: "How it Works",
        benefits: "Benefits",
        for_whom: "For Whom",
        login: "Log in",
        create_account: "Create Account",
        platform_points: "Points Payment Platform",
        future_is_points: "The future of money is based on points.",
        hero_desc: "Convert, send and receive points with the agility of PIX and the security of modern banking technology. Absolute financial simplicity.",
        start_now: "Start Now",
        simple_experience: "Simple Experience",
        real_time_transactions: "Real-time points transactions, no bureaucracy.",
        step1_title: "Create your account",
        step1_desc: "Sign up in seconds and get immediate access to your smart wallet.",
        step2_title: "Receive Points",
        step2_desc: "Receive from partners or convert balance via PIX with minimal fees.",
        step3_title: "Pay with freedom",
        step3_desc: "Use your points throughout the ecosystem with a single click.",
        why_pointify: "Why Pointify?",
        extreme_speed: "Extreme Speed",
        speed_desc: "Synchronous processing to ensure your points arrive on time.",
        total_transparency: "Total Transparency",
        transparency_desc: "Detailed statements with full traceability of each transaction.",
        elite_security: "Elite Security",
        security_desc: "Banking-level encryption and authentication protocols.",
        premium_experience: "Premium Experience",
        minimalism_success: "Minimalism for your financial success",
        terms: "Terms",
        privacy: "Privacy",
        support: "Support",
        all_rights_reserved: "All rights reserved.",
        transaction_alerts: "Transaction Alerts",
        transaction_alerts_desc: "Receive push notifications for every entry/exit",
        news_tips: "News & Tips",
        news_tips_desc: "Promotions and new partners",
        monthly_report: "Monthly Report",
        monthly_report_desc: "Summary of your statement by email",
        main_language: "Main Language",
        reference_currency: "Reference Currency",
        send_points_title: "Send Points",
        recipient_data: "Recipient Data",
        email_or_id: "Email or User ID",
        amount_in_points: "Amount in Points",
        available_balance_label: "Available balance",
        description_optional: "Description (optional)",
        payment_purpose: "What is this payment for?",
        continue_to_review: "Continue to review",
        confirm_send: "Confirm Send",
        you_are_sending: "You are sending",
        to: "To",
        processing_fee: "Processing fee",
        transaction_date: "Transaction date",
        confirm_and_send: "Confirm and Send",
        back_and_edit: "Back and Edit",
        send_completed: "Send completed!",
        transaction_success: "Your transaction of {amount} pts was processed successfully.",
        receipt: "Receipt",
        back_to_start: "Back to start",
        pay_bills: "Pay Bills",
        bills: "Bills",
        pay_titles: "Pay titles",
        pix_keys: "PIX Keys",
        keys: "Keys",
        payment_links: "Payment Links",
        welcome_back: "Welcome back",
        login_desc: "Enter your credentials to access your wallet",
        forgot_password: "Forgot password?",
        no_account: "Don't have an account?",
        sign_in: "Sign in",
        full_name: "Full name",
        your_name: "Your name",
        confirm_password: "Confirm",
        agree_terms: "By signing up, you agree to our Terms and Privacy Policy.",
        already_have_account: "Already have an account?",
        back_to_home: "Back to Home",
        passwords_dont_match: "Passwords don't match!",
        entry: "Entry",
        exit: "Exit",
        receive_points: "Receive Points",
        scan_qr_desc: "Ask the payer to scan this QR Code to send points instantly.",
        share_qr: "Share QR Code",
        your_id: "Your Pointify ID",
        copied_success: "Copied successfully!",
        how_to_receive: "How to receive?",
        receive_step1: "Share your ID or QR Code.",
        receive_step2: "The payer enters the data and confirms the send.",
        receive_step3: "Points arrive in your account in real time.",
        receive_step4: "We will notify you as soon as the balance arrives.",
        copied: "Copied!",
        full_statement: "Full Statement",
        monitor_desc: "Monitor every detail of your wallet",
        export_pdf: "Export PDF",
        search_tx: "Search transaction...",
        all: "All",
        entries: "Entries",
        exits: "Exits",
        filters: "Filters",
        transaction: "Transaction",
        status: "Status",
        value: "Value",
        date_from: "From",
        date_to: "To",
        apply_filters: "Apply Filters",
        reset: "Reset",
        date: "Date",
        create_link: "Create Link",
        help: "Help",
        settings_label: "Settings",
        payment_links_desc: "Create links and receive in DePix",
        min_max: "Min: R$ 20,00 | Max: R$ 3.000,00",
        payment_value: "Payment Value",
        payment_quantity: "Payment Quantity",
        link_closed_after: "The link will be closed after this quantity",
        my_links: "My Links",
        links_created: "{count} links created",
        no_links_yet: "No links created yet",
        create_first_link_desc: "Create your first payment link above",
        summary: "Summary",
        links_active: "Active Links",
        total_received: "Total Received",
        fiscal_report: "Fiscal Report",
        fiscal_report_desc: "View Fiscal Report",
        operational_stable: "OPERATIONAL_STABLE",
        risk_assessment_desc: "Operational status and risk assessment",
        new_profile: "New Profile",
        total_points: "TOTAL POINTS",
        approve: "APPROVE",
        terminate: "TERMINATE",
        session_secure: "Secure Session",
        security_title: "Security",
        custody_subtitle: "Your funds, your custody",
        custody_desc: "Unlike centralized exchanges, you maintain full control of your assets. We are just the bridge — we never hold your funds.",
        no_central_custody_title: "No centralized custody",
        no_central_custody_desc: "Stablecoins are sent directly to your wallet address. You configure, you control.",
        on_chain_transparency_title: "On-chain transparency",
        on_chain_transparency_desc: "All transactions are verifiable on the blockchain. You can audit every movement.",
        no_counterparty_risk_title: "No counterparty risk",
        no_counterparty_risk_desc: "We do not hold client balances. This eliminates risks of hacks, insolvency, or frozen funds.",
    },
    pt: {
        dashboard: "Painel",
        send: "Enviar",
        receive: "Receber",
        history: "Extrato",
        settings: "Ajustes",
        profile: "Perfil",
        available_balance: "Saldo Disponível",
        reserved_balance: "Saldo Reservado",
        recent_transactions: "Últimas Transações",
        quick_actions: "Ações Rápidas",
        send_points: "Enviar Pontos",
        buy: "Comprar",
        view_all: "Ver todas",
        cashback_program: "Programa de Cashback",
        welcome: "Bem-vindo",
        operational_system: "Sistema Operacional",
        premium_user: "Usuário Premium",
        logout: "Sair do sistema",
        send_pix: "Enviar PIX",
        points_to_cash: "Pontos em Dinheiro",
        schedule: "Agendar",
        future_payments: "Futuros Pagamentos",
        cashback_ready: "Você tem 350 pontos prontos para resgate.",
        view_details: "Ver Detalhes",
        admin_panel: "Painel Admin",
        administration: "Administração",
        managing_director: "Sócio Diretor",
        command_center: "Centro de Controle",
        overview: "Visão Geral",
        members: "Membros",
        financial_ledger: "Livro Financeiro",
        auditing: "Auditoria",
        gross_volume: "Volume Bruto (GMV)",
        revenue_spread: "Receita (Spread)",
        avg_ticket: "Ticket Médio",
        daily_flow: "Liquidado Hoje",
        sales_performance: "Fluxo de Performance de Vendas",
        sales_desc: "Volume consolidado por método de captura",
        conversion_rate: "Taxa de Conversão",
        payment_efficiency: "Eficiência de Pagamento",
        export_ledger: "Exportar Ledger",
        search_accounts: "Buscar contas...",
        risk_status: "Status de Risco",
        available_balance_admin: "Saldo Disponível",
        actions: "Ações",
        pix_instant: "Liquidação Instantânea",
        boleto_d2: "Liquidação D+2",
        pointify_links: "Links Pointify",
        backoffice: "Backoffice",
        users: "Usuários",
        finances: "Finanças",
        operational_system_label: "SISTEMA OPERACIONAL",
        main_menu_label: "MENU PRINCIPAL",
        logout_label: "Encerrar Sessão",
        total_control: "Controle Total",
        active_status: "Ativo",
        admin_root: "Admin Root",
        pointify_user: "Usuário Pointify",
        online_now: "Visto agora",
        seen_days_ago: "Há 2 dias",
        revoke: "Revogar",
        notifications: "Notificações",
        lang_region: "Idioma & Região",
        connected_devices: "Dispositivos Conectados",
        discard: "Descartar",
        save_preferences: "Salvar Preferências",
        how_it_works: "Como Funciona",
        benefits: "Benefícios",
        for_whom: "Para Quem",
        login: "Entrar",
        create_account: "Criar Conta",
        platform_points: "Plataforma de Pagamentos por Pontos",
        future_is_points: "O futuro do dinheiro é baseado em pontos.",
        hero_desc: "Converta, envie e receba pontos com a agilidade do PIX e a segurança da tecnologia bancária moderna. Simplicidade financeira absoluta.",
        start_now: "Começar Agora",
        simple_experience: "Experiência Simples",
        real_time_transactions: "Transações de pontos em tempo real, sem burocracia.",
        step1_title: "Crie sua conta",
        step1_desc: "Cadastre-se em segundos e tenha acesso imediato à sua carteira inteligente.",
        step2_title: "Receba Pontos",
        step2_desc: "Receba de parceiros ou converta saldo via PIX com taxas mínimas.",
        step3_title: "Pague com liberdade",
        step3_desc: "Utilize seus pontos em todo o ecossistema com um clique.",
        why_pointify: "Por que Pointify?",
        extreme_speed: "Rapidez Extrema",
        speed_desc: "Processamento síncrono para garantir que seus pontos cheguem na hora.",
        total_transparency: "Transparência Total",
        transparency_desc: "Extratos detalhados com rastreabilidade completa de cada transação.",
        elite_security: "Segurança de Elite",
        security_desc: "Protocolos de criptografia e autenticação de nível bancário.",
        premium_experience: "Experiência Premium",
        minimalism_success: "Minimalismo para o seu sucesso financeiro",
        terms: "Termos",
        privacy: "Privacidade",
        support: "Suporte",
        all_rights_reserved: "Todos os direitos reservados.",
        transaction_alerts: "Alertas de transação",
        transaction_alerts_desc: "Receba push a cada entrada/saída",
        news_tips: "Novidades e Dicas",
        news_tips_desc: "Promoções e novos parceiros",
        monthly_report: "Relatório Mensal",
        monthly_report_desc: "Resumo do seu extrato por email",
        main_language: "Idioma Principal",
        reference_currency: "Moeda de Referência",
        send_points_title: "Enviar Pontos",
        recipient_data: "Dados do destinatário",
        email_or_id: "Email ou ID do usuário",
        amount_in_points: "Valor em pontos",
        available_balance_label: "Saldo disponível",
        description_optional: "Descrição (opcional)",
        payment_purpose: "Para que serve este pagamento?",
        continue_to_review: "Continuar para revisão",
        confirm_send: "Confirmar Envio",
        you_are_sending: "Você está enviando",
        to: "Para",
        processing_fee: "Taxa de processamento",
        transaction_date: "Data da transação",
        confirm_and_send: "Confirmar e Enviar",
        back_and_edit: "Voltar e Editar",
        send_completed: "Envio concluído!",
        transaction_success: "Sua transação de {amount} pts foi processada com sucesso.",
        receipt: "Comprovante",
        back_to_start: "Voltar ao início",
        pay_bills: "Pagar Boletos",
        bills: "Boletos",
        pay_titles: "Pagar títulos",
        pix_keys: "Chaves PIX",
        keys: "Chaves",
        payment_links: "Links de Pagamento",
        welcome_back: "Bem-vindo de volta",
        login_desc: "Insira suas credenciais para acessar sua carteira",
        forgot_password: "Esqueceu a senha?",
        no_account: "Não tem uma conta?",
        sign_in: "Entrar",
        full_name: "Nome completo",
        your_name: "Seu nome",
        confirm_password: "Confirmar",
        agree_terms: "Ao se cadastrar, você concorda com nossos Termos e Política de Privacidade.",
        already_have_account: "Já tem uma conta?",
        back_to_home: "Voltar para Home",
        passwords_dont_match: "As senhas não coincidem!",
        entry: "Entrada",
        exit: "Saída",
        receive_points: "Receber Pontos",
        scan_qr_desc: "Peça para o pagador escanear este QR Code para enviar pontos instantaneamente.",
        share_qr: "Compartilhar QR Code",
        your_id: "Seu ID Pointify",
        copied_success: "Copiado com sucesso!",
        how_to_receive: "Como receber?",
        receive_step1: "Compartilhe seu ID ou QR Code.",
        receive_step2: "O pagador insere os dados e confirma o envio.",
        receive_step3: "Os pontos caem na sua conta em tempo real.",
        receive_step4: "Notificaremos você assim que o saldo chegar.",
        copied: "Copiado!",
        full_statement: "Extrato Completo",
        monitor_desc: "Monitore cada detalhe da sua carteira",
        export_pdf: "Exportar PDF",
        search_tx: "Buscar transação...",
        all: "Tudo",
        entries: "Entradas",
        exits: "Saídas",
        filters: "Filtros",
        transaction: "Transação",
        status: "Status",
        value: "Valor",
        date_from: "De",
        date_to: "Até",
        apply_filters: "Aplicar Filtros",
        reset: "Limpar",
        date: "Data",
        create_link: "Criar Link",
        help: "Ajuda",
        settings_label: "Configurações",
        payment_links_desc: "Crie links e receba em DePix",
        min_max: "Min: R$ 20,00 | Max: R$ 3.000,00",
        payment_value: "Valor do Pagamento",
        payment_quantity: "Quantidade de Pagamentos",
        link_closed_after: "O link será fechado após esta quantidade",
        my_links: "Meus Links",
        links_created: "{count} links criados",
        no_links_yet: "Nenhum link criado ainda",
        create_first_link_desc: "Crie seu primeiro link de pagamento acima",
        summary: "Resumo",
        links_active: "Links Ativos",
        total_received: "Total Recebido",
        fiscal_report: "Relatório Fiscal",
        fiscal_report_desc: "Visualizar Relatório Fiscal",
        operational_stable: "OPERACIONAL_ESTÁVEL",
        risk_assessment_desc: "Status operacional e avaliação de risco",
        new_profile: "Novo Perfil",
        total_points: "TOTAL DE PONTOS",
        approve: "APROVAR",
        terminate: "ENCERRAR",
        session_secure: "Sessão Segura",
        security_title: "Segurança",
        custody_subtitle: "Seus fundos, sua custódia",
        custody_desc: "Diferente de exchanges centralizadas, você mantém controle total dos seus ativos. Nós somos apenas a ponte — nunca mantemos seus fundos.",
        no_central_custody_title: "Sem custódia centralizada",
        no_central_custody_desc: "Stablecoins são enviadas diretamente para o endereço da sua wallet. Você configura, você controla.",
        on_chain_transparency_title: "Transparência on-chain",
        on_chain_transparency_desc: "Todas as transações são verificáveis na blockchain. Você pode auditar cada movimento.",
        no_counterparty_risk_title: "Sem riscos de contraparte",
        no_counterparty_risk_desc: "Não mantemos saldos de clientes. Isso elimina riscos de hacks, insolvência ou congelamento de fundos.",
    },
    es: {
        dashboard: "Panel",
        send: "Enviar",
        receive: "Recibir",
        history: "Historial",
        settings: "Ajustes",
        profile: "Perfil",
        available_balance: "Saldo Disponível",
        reserved_balance: "Saldo Reservado",
        recent_transactions: "Últimas Transações",
        quick_actions: "Ações Rápidas",
        send_points: "Enviar Pontos",
        buy: "Comprar",
        view_all: "Ver todas",
        cashback_program: "Programa de Cashback",
        welcome: "Bem-vindo",
        operational_system: "Sistema Operacional",
        premium_user: "Usuário Premium",
        logout: "Sair do sistema",
        send_pix: "Enviar PIX",
        points_to_cash: "Pontos em Dinheiro",
        schedule: "Agendar",
        future_payments: "Futuros Pagamentos",
        cashback_ready: "Você tem 350 pontos prontos para resgate.",
        view_details: "Ver Detalhes",
        admin_panel: "Painel Admin",
        administration: "Administração",
        managing_director: "Sócio Diretor",
        command_center: "Centro de Controle",
        overview: "Visão Geral",
        members: "Membros",
        financial_ledger: "Livro Financeiro",
        auditing: "Auditoria",
        gross_volume: "Volume Bruto (GMV)",
        revenue_spread: "Receita (Spread)",
        avg_ticket: "Ticket Médio",
        daily_flow: "Liquidado Hoje",
        sales_performance: "Fluxo de Performance de Vendas",
        sales_desc: "Volume consolidado por método de captura",
        conversion_rate: "Taxa de Conversão",
        payment_efficiency: "Eficiência de Pagamento",
        export_ledger: "Exportar Ledger",
        search_accounts: "Buscar contas...",
        risk_status: "Status de Risco",
        available_balance_admin: "Saldo Disponível",
        actions: "Ações",
        pix_instant: "Liquidação Instantânea",
        boleto_d2: "Liquidação D+2",
        pointify_links: "Links Pointify",
        backoffice: "Backoffice",
        users: "Usuários",
        finances: "Finanças",
        operational_system_label: "SISTEMA OPERACIONAL",
        main_menu_label: "MENU PRINCIPAL",
        logout_label: "Encerrar Sessão",
        total_control: "Controle Total",
        active_status: "Ativo",
        admin_root: "Admin Root",
        pointify_user: "Usuário Pointify",
        online_now: "Visto agora",
        seen_days_ago: "Há 2 dias",
        revoke: "Revogar",
        notifications: "Notificações",
        lang_region: "Idioma & Região",
        connected_devices: "Dispositivos Conectados",
        discard: "Descartar",
        save_preferences: "Salvar Preferências",
        how_it_works: "Como Funciona",
        benefits: "Benefícios",
        for_whom: "Para Quem",
        login: "Entrar",
        create_account: "Criar Conta",
        platform_points: "Plataforma de Pagamentos por Pontos",
        future_is_points: "O futuro do dinheiro é baseado em pontos.",
        hero_desc: "Converta, envie e receba pontos com a agilidade do PIX e a segurança da tecnologia bancária moderna. Simplicidade financeira absoluta.",
        start_now: "Começar Agora",
        simple_experience: "Experiência Simples",
        real_time_transactions: "Transações de pontos em tempo real, sem burocracia.",
        step1_title: "Crie sua conta",
        step1_desc: "Cadastre-se em segundos e tenha acesso imediato à sua carteira inteligente.",
        step2_title: "Receba Pontos",
        step2_desc: "Receba de parceiros ou converta saldo via PIX com taxas mínimas.",
        step3_title: "Pague com liberdade",
        step3_desc: "Utilize seus pontos em todo o ecossistema com um clique.",
        why_pointify: "Por que Pointify?",
        extreme_speed: "Rapidez Extrema",
        speed_desc: "Processamento síncrono para garantir que seus pontos cheguem na hora.",
        total_transparency: "Transparência Total",
        transparency_desc: "Extratos detalhados com rastreabilidade completa de cada transação.",
        elite_security: "Segurança de Elite",
        security_desc: "Protocolos de criptografia e autenticação de nível bancário.",
        premium_experience: "Experiência Premium",
        minimalism_success: "Minimalismo para o seu sucesso financeiro",
        terms: "Termos",
        privacy: "Privacidade",
        support: "Suporte",
        all_rights_reserved: "Todos os direitos reservados.",
        transaction_alerts: "Alertas de transação",
        transaction_alerts_desc: "Receba push a cada entrada/saída",
        news_tips: "Novidades e Dicas",
        news_tips_desc: "Promoções e novos parceiros",
        monthly_report: "Relatório Mensal",
        monthly_report_desc: "Resumo do seu extrato por email",
        main_language: "Idioma Principal",
        reference_currency: "Moeda de Referência",
        send_points_title: "Enviar Pontos",
        recipient_data: "Dados do destinatário",
        email_or_id: "Email ou ID do usuário",
        amount_in_points: "Valor em pontos",
        available_balance_label: "Saldo disponível",
        description_optional: "Descrição (opcional)",
        payment_purpose: "Para que serve este pagamento?",
        continue_to_review: "Continuar para revisão",
        confirm_send: "Confirmar Envio",
        you_are_sending: "Você está enviando",
        to: "Para",
        processing_fee: "Taxa de processamento",
        transaction_date: "Data da transação",
        confirm_and_send: "Confirmar e Enviar",
        back_and_edit: "Voltar e Editar",
        send_completed: "Envio concluído!",
        transaction_success: "Sua transação de {amount} pts foi processada com sucesso.",
        receipt: "Comprovante",
        back_to_start: "Voltar ao início",
        pay_bills: "Pagar Boletos",
        bills: "Boletos",
        pay_titles: "Pagar títulos",
        pix_keys: "Chaves PIX",
        keys: "Chaves",
        payment_links: "Links de Pagamento",
        welcome_back: "Bem-vindo de volta",
        login_desc: "Insira suas credenciais para acessar sua carteira",
        forgot_password: "Esqueceu a senha?",
        no_account: "Não tem uma conta?",
        sign_in: "Entrar",
        full_name: "Nome completo",
        your_name: "Seu nome",
        confirm_password: "Confirmar",
        agree_terms: "Ao se cadastrar, você concorda com nossos Termos e Política de Privacidade.",
        already_have_account: "Já tem uma conta?",
        back_to_home: "Voltar para Home",
        passwords_dont_match: "As senhas não coincidem!",
        entry: "Entrada",
        exit: "Saída",
        receive_points: "Receber Pontos",
        scan_qr_desc: "Peça para o pagador escanear este QR Code para enviar pontos instantaneamente.",
        share_qr: "Compartilhar QR Code",
        your_id: "Seu ID Pointify",
        copied_success: "Copiado com sucesso!",
        how_to_receive: "Como receber?",
        receive_step1: "Compartilhe seu ID ou QR Code.",
        receive_step2: "O pagador insere os dados e confirma o envio.",
        receive_step3: "Os pontos caem na sua conta em tempo real.",
        receive_step4: "Notificaremos você assim que o saldo chegar.",
        copied: "Copiado!",
        full_statement: "Extrato Completo",
        monitor_desc: "Monitore cada detalhe da sua carteira",
        export_pdf: "Exportar PDF",
        search_tx: "Buscar transação...",
        all: "Tudo",
        entries: "Entradas",
        exits: "Saídas",
        filters: "Filtros",
        transaction: "Transação",
        status: "Status",
        value: "Valor",
        date_from: "De",
        date_to: "Até",
        apply_filters: "Aplicar Filtros",
        reset: "Limpar",
        date: "Data",
        create_link: "Criar Link",
        help: "Ajuda",
        settings_label: "Configurações",
        payment_links_desc: "Crie links e receba em DePix",
        min_max: "Min: R$ 20,00 | Max: R$ 3.000,00",
        payment_value: "Valor do Pagamento",
        payment_quantity: "Quantidade de Pagamentos",
        link_closed_after: "O link será fechado após esta quantidade",
        my_links: "Meus Links",
        links_created: "{count} links criados",
        no_links_yet: "Nenhum link criado ainda",
        create_first_link_desc: "Crie seu primeiro link de pagamento acima",
        summary: "Resumo",
        links_active: "Links Ativos",
        total_received: "Total Recebido",
        fiscal_report: "Relatório Fiscal",
        fiscal_report_desc: "Visualizar Relatório Fiscal",
        operational_stable: "OPERACIONAL_ESTÁVEL",
        risk_assessment_desc: "Status operacional e avaliação de risco",
        new_profile: "Novo Perfil",
        total_points: "TOTAL DE PONTOS",
        approve: "APROVAR",
        terminate: "ENCERRAR",
        session_secure: "Sessão Segura",
    },
    es: {
        dashboard: "Panel",
        send: "Enviar",
        receive: "Recibir",
        history: "Historial",
        settings: "Ajustes",
        profile: "Perfil",
        available_balance: "Saldo Disponible",
        reserved_balance: "Saldo Reservado",
        recent_transactions: "Últimas Transacciones",
        quick_actions: "Acciones Rápidas",
        send_points: "Enviar Puntos",
        buy: "Comprar",
        view_all: "Ver todas",
        cashback_program: "Programa de Cashback",
        welcome: "Bienvenido",
        operational_system: "Sistema Operativo",
        premium_user: "Usuario Premium",
        logout: "Cerrar sesión",
        send_pix: "Enviar PIX",
        points_to_cash: "Puntos en Efectivo",
        schedule: "Agendar",
        future_payments: "Pagos Futuros",
        cashback_ready: "Tienes 350 puntos listos para canjear.",
        view_details: "Ver Detalles",
        admin_panel: "Panel Admin",
        administration: "Administración",
        managing_director: "Socio Director",
        command_center: "Centro de Control",
        overview: "Visión General",
        members: "Miembros",
        financial_ledger: "Libro Financiero",
        auditing: "Auditoría",
        gross_volume: "Volumen Bruto (GMV)",
        revenue_spread: "Ingresos (Spread)",
        avg_ticket: "Ticket Promedio",
        daily_flow: "Liquidado Hoy",
        sales_performance: "Flujo de Rendimiento de Ventas",
        sales_desc: "Volumen consolidado por método de captura",
        conversion_rate: "Tasa de Conversión",
        payment_efficiency: "Eficiencia de Pago",
        export_ledger: "Exportar Ledger",
        search_accounts: "Buscar cuentas...",
        risk_status: "Estado de Riesgo",
        available_balance_admin: "Saldo Disponible",
        actions: "Acciones",
        pix_instant: "Liquidación Instantánea",
        boleto_d2: "Liquidación D+2",
        pointify_links: "Enlaces Pointify",
        backoffice: "Backoffice",
        users: "Usuarios",
        finances: "Finanzas",
        operational_system_label: "SISTEMA OPERATIVO",
        main_menu_label: "MENÚ PRINCIPAL",
        logout_label: "Cerrar Sesión",
        total_control: "Control Total",
        active_status: "Activo",
        admin_root: "Admin Root",
        pointify_user: "Usuario Pointify",
        online_now: "Visto ahora",
        seen_days_ago: "Hace 2 días",
        revoke: "Revocar",
        notifications: "Notificaciones",
        lang_region: "Idioma & Región",
        connected_devices: "Dispositivos Conectados",
        discard: "Descartar",
        save_preferences: "Guardar Preferencias",
        how_it_works: "Cómo Funciona",
        benefits: "Beneficios",
        for_whom: "Para Quién",
        login: "Entrar",
        create_account: "Crear Cuenta",
        platform_points: "Plataforma de Pagos por Puntos",
        future_is_points: "El futuro del dinero está basado en puntos.",
        hero_desc: "Convierte, envía y recibe puntos con la agilidad de PIX y la seguridad de la tecnología bancaria moderna. Simplicidad financiera absoluta.",
        start_now: "Empezar Ahora",
        simple_experience: "Experiencia Simple",
        real_time_transactions: "Transacciones de puntos en tiempo real, sin burocracia.",
        step1_title: "Crea tu cuenta",
        step1_desc: "Regístrate en segundos y obtén acceso inmediato a tu billetera inteligente.",
        step2_title: "Recibe Puntos",
        step2_desc: "Recibe de socios o convierte saldo vía PIX con tasas mínimas.",
        step3_title: "Paga con libertad",
        step3_desc: "Utiliza tus puntos en todo el ecosistema con un solo clic.",
        why_pointify: "¿Por qué Pointify?",
        extreme_speed: "Rapidez Extrema",
        speed_desc: "Procesamiento síncrono para garantir que tus puntos lleguen a tiempo.",
        total_transparency: "Transparencia Total",
        transparency_desc: "Extractos detallados con trazabilidad completa de cada transacción.",
        elite_security: "Seguridad de Élite",
        security_desc: "Protocolos de criptografía y autenticación de nivel bancario.",
        premium_experience: "Experiencia Premium",
        minimalism_success: "Minimalismo para tu éxito financiero",
        terms: "Términos",
        privacy: "Privacidad",
        support: "Soporte",
        all_rights_reserved: "Todos los derechos reservados.",
        transaction_alerts: "Alertas de transacción",
        transaction_alerts_desc: "Recibe push a cada entrada/salida",
        news_tips: "Novedades y Consejos",
        news_tips_desc: "Promociones e nuevos socios",
        monthly_report: "Reporte Mensual",
        monthly_report_desc: "Resumen de su extracto por email",
        main_language: "Idioma Principal",
        reference_currency: "Moneda de Referencia",
        send_points_title: "Enviar Puntos",
        recipient_data: "Datos del destinatario",
        email_or_id: "Email o ID del usuario",
        amount_in_points: "Valor en puntos",
        available_balance_label: "Saldo disponible",
        description_optional: "Descripción (opcional)",
        payment_purpose: "¿Para qué sirve este pago?",
        continue_to_review: "Continuar para revisión",
        confirm_send: "Confirmar Envío",
        you_are_sending: "Estás enviando",
        to: "Para",
        processing_fee: "Tasa de procesamiento",
        transaction_date: "Fecha de la transacción",
        confirm_and_send: "Confirmar y Enviar",
        back_and_edit: "Volver y Editar",
        send_completed: "¡Envío completado!",
        transaction_success: "Su transacción de {amount} pts fue procesada con éxito.",
        receipt: "Comprobante",
        back_to_start: "Volver al inicio",
        pay_bills: "Pagar Facturas",
        bills: "Facturas",
        pay_titles: "Pagar títulos",
        pix_keys: "Claves PIX",
        keys: "Claves",
        payment_links: "Links de Pago",
        welcome_back: "Bienvenido de nuevo",
        login_desc: "Ingrese sus credenciales para acceder a su billetera",
        forgot_password: "¿Olvidó su contraseña?",
        no_account: "¿No tiene una cuenta?",
        sign_in: "Entrar",
        full_name: "Nombre completo",
        your_name: "Su nombre",
        confirm_password: "Confirmar",
        agree_terms: "Al registrarse, acepta nuestros Términos y Política de Privacidad.",
        already_have_account: "¿Ya tiene una cuenta?",
        back_to_home: "Volver a Inicio",
        passwords_dont_match: "¡Las contraseñas no coinciden!",
        entry: "Entrada",
        exit: "Salida",
        receive_points: "Recibir Puntos",
        scan_qr_desc: "Pida al pagador que escanee este código QR para enviar puntos al instante.",
        share_qr: "Compartir código QR",
        your_id: "Tu ID de Pointify",
        copied_success: "¡Copiado con éxito!",
        how_to_receive: "¿Cómo recibir?",
        receive_step1: "Comparte tu ID o código QR.",
        receive_step2: "El pagador ingresa los datos y confirma el envío.",
        receive_step3: "Los puntos llegan a tu cuenta en tiempo real.",
        receive_step4: "Le notificaremos tan pronto como llegue el saldo.",
        copied: "¡Copiado!",
        full_statement: "Extracto Completo",
        monitor_desc: "Monitorea cada detalle de tu billetera",
        export_pdf: "Exportar PDF",
        search_tx: "Buscar transacción...",
        all: "Todo",
        entries: "Entradas",
        exits: "Salidas",
        filters: "Filtros",
        transaction: "Transacción",
        status: "Estado",
        value: "Valor",
        date_from: "Desde",
        date_to: "Hasta",
        apply_filters: "Aplicar Filtros",
        reset: "Limpiar",
        date: "Fecha",
        create_link: "Crear Link",
        help: "Ayuda",
        settings_label: "Configuraciones",
        payment_links_desc: "Crea links y recibe en DePix",
        min_max: "Mín: R$ 20,00 | Máx: R$ 3.000,00",
        payment_value: "Valor del Pago",
        payment_quantity: "Cantidad de Pagos",
        link_closed_after: "El link se cerrará después de esta cantidad",
        my_links: "Mis Links",
        links_created: "{count} links creados",
        no_links_yet: "Ningún link creado todavía",
        create_first_link_desc: "Crea tu primer link de pago arriba",
        summary: "Resumen",
        links_active: "Links Activos",
        total_received: "Total Recibido",
        fiscal_report: "Informe Fiscal",
        fiscal_report_desc: "Ver Informe Fiscal",
        operational_stable: "OPERACIONAL_ESTABLE",
        risk_assessment_desc: "Estado operativo y evaluación de riesgos",
        new_profile: "Nuevo Perfil",
        total_points: "TOTAL DE PUNTOS",
        approve: "APROBAR",
        terminate: "TERMINAR",
        session_secure: "Sesión Segura",
        security_title: "Seguridad",
        custody_subtitle: "Sus fondos, su custodia",
        custody_desc: "A diferencia de los intercambios centralizados, usted mantiene el control total de sus activos. Somos solo el puente: nunca retenemos sus fondos.",
        no_central_custody_title: "Sin custodia centralizada",
        no_central_custody_desc: "Las stablecoins se envían directamente a la dirección de su billetera. Usted configura, usted controla.",
        on_chain_transparency_title: "Transparencia on-chain",
        on_chain_transparency_desc: "Todas las transacciones son verificables en la blockchain. Puede auditar cada movimiento.",
        no_counterparty_risk_title: "Sin riesgo de contraparte",
        no_counterparty_risk_desc: "No mantenemos saldos de clientes. Esto elimina riesgos de hacks, insolvencia o congelación de fondos.",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("pt");

    useEffect(() => {
        const saved = localStorage.getItem("language") as Language;
        if (saved && (saved === "en" || saved === "pt" || saved === "es")) {
            setLanguage(saved);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string) => {
        return translations[language][key as keyof (typeof translations)["en"]] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
